@startuml
title TemplateMethodパターンクラス図

' 抽象クラス役
abstract class AbstractClass{
    method1()
    method2()
    method3()
    templateMethod()
}
note left: AbstractDisplay

' 具象クラス
class Concrete1Class{
    method1()
    method2()
    method3()
}
note right: CharDisplay

' 抽象クラス2
class Concrete2Class{
    method1()
    method2()
    method3()
}
note right: StringDisplay

' 配置指定
AbstractClass <|-- Concrete1Class : extends
AbstractClass <|-- Concrete2Class : extends

@enduml